### ISSUE TITLE
Error publishing new version

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-plugin-gdc#12]
I thought it would be good to get a new fixed version out as we think about cancer applications

Running yarn publish however gives an error, may be a minor thing related to prop types

```
● GDCTrack widget › renders mutation with just the required model elements

    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `GDCFeatureDetails`.

      67 |     /* eslint-enable @typescript-eslint/camelcase */
      68 |
    > 69 |     const { container } = render(<GDCFeatureDetails model={f} />)
         |                           ^
      70 |     expect(container.firstChild).toMatchSnapshot()
      71 |   })
      72 |

      at createFiberFromTypeAndProps (node_modules/react-dom/cjs/react-dom.development.js:23965:21)
      at createFiberFromElement (node_modules/react-dom/cjs/react-dom.development.js:23988:15)
      at createChild (node_modules/react-dom/cjs/react-dom.development.js:13628:28)
      at reconcileChildrenArray (node_modules/react-dom/cjs/react-dom.development.js:13900:25)
      at reconcileChildFibers (node_modules/react-dom/cjs/react-dom.development.js:14305:14)
      at reconcileChildren (node_modules/react-dom/cjs/react-dom.development.js:16762:28)
      at updateHostComponent (node_modules/react-dom/cjs/react-dom.development.js:17302:3)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:18627:14)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23203:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22157:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22130:22)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21756:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at node_modules/@testing-library/react/dist/pure.js:99:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at render (node_modules/@testing-library/react/dist/pure.js:95:26)
      at Object.<anonymous> (src/GDCFeatureWidget/GDCFeatureWidget.test.js:69:27)

  ● GDCTrack widget › renders gene with just the required model elements

    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `GDCFeatureDetails`.

      104 |     })
      105 |
    > 106 |     const { container } = render(<GDCFeatureDetails model={f} />)
          |                           ^
      107 |     expect(container.firstChild).toMatchSnapshot()
      108 |   })
      109 | })

      at createFiberFromTypeAndProps (node_modules/react-dom/cjs/react-dom.development.js:23965:21)
      at createFiberFromElement (node_modules/react-dom/cjs/react-dom.development.js:23988:15)
      at createChild (node_modules/react-dom/cjs/react-dom.development.js:13628:28)
      at reconcileChildrenArray (node_modules/react-dom/cjs/react-dom.development.js:13900:25)
      at reconcileChildFibers (node_modules/react-dom/cjs/react-dom.development.js:14305:14)
      at reconcileChildren (node_modules/react-dom/cjs/react-dom.development.js:16762:28)
      at updateHostComponent (node_modules/react-dom/cjs/react-dom.development.js:17302:3)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:18627:14)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23203:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22157:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22130:22)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21756:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at node_modules/@testing-library/react/dist/pure.js:99:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at render (node_modules/@testing-library/react/dist/pure.js:95:26)
      at Object.<anonymous> (src/GDCFeatureWidget/GDCFeatureWidget.test.js:106:27)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `GDCFeatureDetails`.
        in GDCFeatureDetails

      595 |     return (
      596 |       <Paper className={classes.root} data-testid="variant-widget">
    > 597 |         <FeatureDetails feature={rest} {...props} />
          |         ^
      598 |         <Divider />
      599 |         {feat.geneId && <GeneExternalLinks feature={feat} />}
      600 |         {feat.ssmId && <SSMExternalLinks feature={feat} />}

      at printWarning (node_modules/react/cjs/react.development.js:315:30)
      at error (node_modules/react/cjs/react.development.js:287:5)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1788:7)
      at GDCFeatureDetails (src/GDCFeatureWidget/GDCFeatureWidget.js:597:9)
      at node_modules/mobx-react-lite/lib/observer.js:26:63
      at node_modules/mobx-react-lite/lib/useObserver.js:96:29
      at trackDerivedFunction (node_modules/mobx/lib/mobx.js:776:24)

  console.error
    Error: Uncaught [Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `GDCFeatureDetails`.]
        at reportException (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
        at invokeEventListeners (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLUnknownElementImpl._dispatch (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLUnknownElement.dispatchEvent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at Object.invokeGuardedCallbackDev (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:22157:12) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `GDCFeatureDetails`.
        at createFiberFromTypeAndProps (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:23965:21)
        at createFiberFromElement (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:23988:15)
        at createChild (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:13628:28)
        at reconcileChildrenArray (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:13900:25)
        at reconcileChildFibers (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:14305:14)
        at reconcileChildren (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:16762:28)
        at updateHostComponent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:17302:3)
        at beginWork (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:18627:14)
        at HTMLUnknownElement.callCallback (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:188:14)
        at innerInvokeEventListeners (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
        at invokeEventListeners (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLUnknownElementImpl._dispatch (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLUnknownElement.dispatchEvent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at Object.invokeGuardedCallbackDev (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
        at workLoopSync (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
        at performSyncWorkOnRoot (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:21756:9)
        at scheduleUpdateOnFiber (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:21188:7)
        at updateContainer (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:24373:3)
        at /home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:24758:7
        at unbatchedUpdates (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:21903:12)
        at legacyRenderSubtreeIntoContainer (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:24757:5)
        at Object.render (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:24840:10)
        at /home/cdiesh/src/jbrowse-plugin-gdc/node_modules/@testing-library/react/dist/pure.js:99:25
        at batchedUpdates$1 (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
        at act (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
        at render (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/@testing-library/react/dist/pure.js:95:26)
        at Object.<anonymous> (/home/cdiesh/src/jbrowse-plugin-gdc/src/GDCFeatureWidget/GDCFeatureWidget.test.js:69:27)
        at Object.asyncJestTest (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
        at /home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jest-jasmine2/build/queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at /home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jest-jasmine2/build/queueRunner.js:75:41
        at processTicksAndRejections (node:internal/process/task_queues:94:5)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)

  console.error
    The above error occurred in the <div> component:
        in div (created by ForwardRef(Paper))
        in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
        in WithStyles(ForwardRef(Paper)) (created by GDCFeatureDetails)
        in GDCFeatureDetails

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:19527:21)
      at logError (node_modules/react-dom/cjs/react-dom.development.js:19564:5)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:20708:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:12490:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:12511:9)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19883:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `GDCFeatureDetails`.
        in GDCFeatureDetails

      595 |     return (
      596 |       <Paper className={classes.root} data-testid="variant-widget">
    > 597 |         <FeatureDetails feature={rest} {...props} />
          |         ^
      598 |         <Divider />
      599 |         {feat.geneId && <GeneExternalLinks feature={feat} />}
      600 |         {feat.ssmId && <SSMExternalLinks feature={feat} />}

      at printWarning (node_modules/react/cjs/react.development.js:315:30)
      at error (node_modules/react/cjs/react.development.js:287:5)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1788:7)
      at GDCFeatureDetails (src/GDCFeatureWidget/GDCFeatureWidget.js:597:9)
      at node_modules/mobx-react-lite/lib/observer.js:26:63
      at node_modules/mobx-react-lite/lib/useObserver.js:96:29
      at trackDerivedFunction (node_modules/mobx/lib/mobx.js:776:24)

  console.error
    Error: Uncaught [Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `GDCFeatureDetails`.]
        at reportException (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
        at invokeEventListeners (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLUnknownElementImpl._dispatch (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLUnknownElement.dispatchEvent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at Object.invokeGuardedCallbackDev (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:22157:12) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `GDCFeatureDetails`.
        at createFiberFromTypeAndProps (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:23965:21)
        at createFiberFromElement (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:23988:15)
        at createChild (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:13628:28)
        at reconcileChildrenArray (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:13900:25)
        at reconcileChildFibers (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:14305:14)
        at reconcileChildren (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:16762:28)
        at updateHostComponent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:17302:3)
        at beginWork (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:18627:14)
        at HTMLUnknownElement.callCallback (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:188:14)
        at innerInvokeEventListeners (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
        at invokeEventListeners (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLUnknownElementImpl._dispatch (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLUnknownElement.dispatchEvent (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at Object.invokeGuardedCallbackDev (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
        at workLoopSync (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
        at performSyncWorkOnRoot (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:21756:9)
        at scheduleUpdateOnFiber (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:21188:7)
        at updateContainer (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:24373:3)
        at /home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:24758:7
        at unbatchedUpdates (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:21903:12)
        at legacyRenderSubtreeIntoContainer (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:24757:5)
        at Object.render (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:24840:10)
        at /home/cdiesh/src/jbrowse-plugin-gdc/node_modules/@testing-library/react/dist/pure.js:99:25
        at batchedUpdates$1 (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
        at act (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
        at render (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/@testing-library/react/dist/pure.js:95:26)
        at Object.<anonymous> (/home/cdiesh/src/jbrowse-plugin-gdc/src/GDCFeatureWidget/GDCFeatureWidget.test.js:106:27)
        at Object.asyncJestTest (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
        at /home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jest-jasmine2/build/queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (/home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at /home/cdiesh/src/jbrowse-plugin-gdc/node_modules/jest-jasmine2/build/queueRunner.js:75:41
        at processTicksAndRejections (node:internal/process/task_queues:94:5)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)

  console.error
    The above error occurred in the <div> component:
        in div (created by ForwardRef(Paper))
        in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
        in WithStyles(ForwardRef(Paper)) (created by GDCFeatureDetails)
        in GDCFeatureDetails

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:19527:21)
      at logError (node_modules/react-dom/cjs/react-dom.development.js:19564:5)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:20708:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:12490:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:12511:9)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19883:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        2.741s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.

```

**Comment by cmdcolin** [comment]
needed to pass a pseudo-session to the gdc test and update jbrowse/core devDependency

**Comment by cmdcolin** [comment]
v1.0.4 published :)
